chore: add setup files
yobst/heisse-preise-de pull request #2
Opened 2023-11-08 14:06 UTC by jsmassa

2023-11-10 09:02 UTC, TimoKramer requested changes

2023-11-10 09:02 UTC, TimoKramer commented on Dockerfile
> +WORKDIR /heisse-preise-de/
You could put the entrypoint in here and a default cmd as well
```suggestion
WORKDIR /heisse-preise-de/

EXPOSE 3000

LABEL org.opencontainers.image.source=https://github.com/yobst/heisse-preise-de
LABEL org.opencontainers.image.description="Yobst Price Scraper"

ENTRYPOINT npm
CMD ["run", "start"]
```

2023-11-10 09:02 UTC, TimoKramer commented on README.md
> +docker run --volume=$(pwd):/heisse-preise-de --volume=$(pwd)/data/:/heisse-preise-de/data --publish 3000:3000 --entrypoint npm localhost/heisse-preise-de_site:latest run dev
```suggestion
docker run --volume=$(pwd):/heisse-preise-de --volume=$(pwd)/data/:/heisse-preise-de/data --publish 3000:3000  localhost/heisse-preise-de_site:latest run dev
```

2023-11-10 09:02 UTC, TimoKramer commented on README.md
> +docker run --volume=$(pwd):/heisse-preise-de --volume=$(pwd)/data/:/heisse-preise-de/data --publish 3000:3000 --entrypoint npm localhost/heisse-preise-de_site:latest run start
```suggestion
docker run --volume=$(pwd):/heisse-preise-de --volume=$(pwd)/data/:/heisse-preise-de/data --publish 3000:3000 localhost/heisse-preise-de_site:latest
```

2023-11-10 11:34 UTC, jsmassa commented on Dockerfile
> +WORKDIR /heisse-preise-de/
Changed it accordingly

2023-11-10 11:35 UTC, jsmassa commented on README.md
> +docker run --volume=$(pwd):/heisse-preise-de --volume=$(pwd)/data/:/heisse-preise-de/data --publish 3000:3000 --entrypoint npm localhost/heisse-preise-de_site:latest run dev
I have updated the commands.

2023-11-10 11:35 UTC, jsmassa commented on README.md
> +docker run --volume=$(pwd):/heisse-preise-de --volume=$(pwd)/data/:/heisse-preise-de/data --publish 3000:3000 --entrypoint npm localhost/heisse-preise-de_site:latest run start
Changed.

2023-11-10 12:09 UTC, TimoKramer approved these changes

2023-11-10 12:09 UTC, TimoKramer commented on README.md
> +docker run --volume=$(pwd):/heisse-preise-de --volume=$(pwd)/data/:/heisse-preise-de/data localhost/heisse-preise-de_site:latest run start
run start is now the default and is not needed here anymore

2023-11-10 12:32 UTC, jsmassa commented on README.md
> +docker run --volume=$(pwd):/heisse-preise-de --volume=$(pwd)/data/:/heisse-preise-de/data localhost/heisse-preise-de_site:latest run start
I know, I only left it in so the difference is obvious. But I can add the alternative.

I found an issue with the `npm run start` though as the scripts have changed in this version of the project and `start` has been dropped - in favor of a [separate build](https://github.com/yobst/heisse-preise-de/blob/7d859895662ad0136ce6359f181c58a75a56e629/package.json#L15) process if I understand it correctly. 

I would add `npm run build` to the dockerfile then and set `npm run server` as the default command. Or what do you think?

2023-11-10 16:43 UTC, jsmassa commented on README.md
> +docker run --volume=$(pwd):/heisse-preise-de --volume=$(pwd)/data/:/heisse-preise-de/data localhost/heisse-preise-de_site:latest run start
I have added a build stage now to the Dockerfile. 

I also dropped the documentation about running dev mode inside the container. Shouldn't be needed anyway. The documented command for production and staging is now shortened and corrected.

2023-11-15 13:02 UTC, TimoKramer approved these changes

2023-11-15 13:02 UTC, merged